<?php 
/*
 * Copyright 2013 by Sawyer Bowman, Jim Garvey, Kevin Tabb, Nick Wetzel, and Allen
 * Tucker.  This program is part of Homeplate, which is free software.  It comes
 * with absolutely no warranty.  You can redistribute and/or modify it under the
 * terms of the GNU Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/).
 */

/** 
 * User documentation for report generation in MCH Homeplate
 * @author Jim Garvey
 * @version Dec 2013
 */

?>

<!DOCTYPE html>
<html>
<head>
	<title>Report Generation Help</title>
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>

<body>
	
	<h1>Generating and Exporting Reports</h1>
	
	<p> The reports section of Homeplate is used to generate information about the food processed by the Mid Coast Hunger Prevention Program. 
	Reports can be generated using a variety of different parameters. These parameters include an option of donor type (individual or organization), 
	a choice or report type (total weight or breakdown), a single donor option, and finally a date range. Follow the steps below to generate a report.</p> 
	
	<p> <b>Step 1:</b> Navigate to the reports page by clicking on the reports link in the menu bar (2nd from the right)</p><br><br>
	<a href="tutorial/screenshots/homeplate_reports_1.png" class="centered" title="homeplate_reports_1" style="width:500px; display:block;">
		<img class="centered" src="tutorial/screenshots/homeplate_reports_1.png" style="display:block; width:500px; border-width:1px; border-style:solid">
	</a>

	<p> <b>Step 2:</b> Select the parameters for the report. Select a donor type, report type, and the time period for the report. 
	The time for the report can be selected by clicking on one of the radio buttons to the left of the options. The options are last week, 
	a single day, or a custom date range. If selecting a single day or date range, the desired date(s) must be selected from the drop down menus. 
	Optionally a donor name may also be provided. </p><br><br>
    <a href="tutorial/screenshots/homeplate_reports_2.png" class="centered" title="homeplate_reports_2" style="width:500px; display:block;">
		<img class="centered" src="tutorial/screenshots/homeplate_reports_2.png" style="display:block; width:500px; border-width:1px; border-style:solid">
	</a>
	
	
	<p> <b>Step 3:</b> Once the desired parameters have been selected, click on the generate report button towards the bottom of the page. 
	The report information will be presented on the bottom of the same page. Here is an example of this. </p> <br><br>
	<a href="tutorial/screenshots/homeplate_reports_3.png" class="centered" title="homeplate_reports_3" style="width:500px; display:block;">
		<img class="centered" src="tutorial/screenshots/homeplate_reports_3.png" style="display:block; width:500px; border-width:1px; border-style:solid">
	</a>
	
	<p> <b>Step 4:</b> The data generated by homeplate can be exported in either PDF or CSV (comma separated value) format. The CSV file can easily be imported
	into excel or another spreadsheet program. The PDF format is useful for printing out the data. To export this data click on one of the links next to the table. 
	
</body>
</html>


	
	
	
	