<!--
/*
 * Copyright 2014 by ... and Allen Tucker.
 * This program is part of Homerestore, which is free software.  It comes 
 * with absolutely no warranty.  You can redistribute and/or modify it under the 
 * terms of the GNU Public License as published by the Free Software Foundation 
 * (see <http://www.gnu.org/licenses/).
*/
-->

<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2015 by Moustafa El Badry, Noah Jensen, Dylan Martin, Luis Munguia Orta, David Quennoz, and Allen Tucker.<br />
	<i>BMAC-Warehouse</i> is being developed
	for <a href="http://bmacww.org" target="_BLANK" style="font-weight:normal;">the Blue Mountain Action Council (BMAC) </a>
	in Walla Walla, WA. <i>BMAC-Warehouse</i> is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	<a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;" target="_blank"> GNU General Public License</a>.
	</p>
</div>
</div>
<!-- End Footer -->