<!--
/*
 * Copyright 2013 by Sawyer Bowman, Jim Garvey, Kevin Tabb, Nick Wetzel, and Allen 
 * Tucker.  This program is part of Homerestore, which is free software.  It comes 
 * with absolutely no warranty.  You can redistribute and/or modify it under the 
 * terms of the GNU Public License as published by the Free Software Foundation 
 * (see <http://www.gnu.org/licenses/).
*/
-->

<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2014-2015 by Sawyer Bowman, Jim Garvey, Kevin Tabb, Nick Wetzel, and Allen Tucker.<br />
	<i>Homerestore</i> is being developed
	for <a href="http://www.habitathhi.org/restore.htm" target="_BLANK" style="font-weight:normal;">the Habitat for Humanity Resale Store</a>
	in Bluffton, South Carolina. <i>Homerestore</i> is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	<a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;" target="_blank"> GNU General Public License</a>.
	</p>
</div>
</div>
<!-- End Footer -->