<?PHP

/*
 * Copyright 2013 by Sawyer Bowman, Jim Garvey, Kevin Tabb, Nick Wetzel, and Allen
 * Tucker.  This program is part of Homerestore, which is free software.  It comes
 * with absolutely no warranty.  You can redistribute and/or modify it under the
 * terms of the GNU Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/).
 */

	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Help - <?PHP echo($_GET['helpPage']); ?>
		</title>
		<link rel="stylesheet" href="tutorial/styles.css" type="text/css" />
	</head>

	<body>
		<div id="container">
			<div id="content">
				<div align="left"><p><a href="?">Homerestore Help</a></p></div>

				<?PHP
					//This array associates pages a person might be viewing
					//with the help page we assume they want. Note: it might be important
					//for each page to include within it a link to the 'home help' website
					//to allow us to get them to material somewhere else they might want.
					//you can guarantee a link to the home site by simply linking to
					//help.php with no variable passed through the GET method.
				
					//basic pages
					$assocHelp['index.php']='index.inc.php';
					$assocHelp['about.php']='index.inc.php';

					//working with donations
					$assocHelp['viewDonation1.php']='donationViewHelp.inc.php';
					$assocHelp['viewDonation2.php']='donationViewHelp.inc.php';
					$assocHelp['donationLogView.php']='donationLogViewHelp.inc.php';
					
					//donor editing, searching, viewing
					$assocHelp['donorSearch.php']='searchDonorHelp.inc.php';
					$assocHelp['donorEdit.php']='editDonorHelp.inc.php';
					$assocHelp['donorForm.php']='addDonorHelp.inc.php';
					
					//reports
					$assocHelp['viewReports.php']='viewReportsHelp.inc.php';


					//Now if we have an undefined array value for the key they've passed us
					//what happens? This means that the page they're looking for help on doesn't have a
					//specific help page we defined above. So we pass them to the index page to see if they can find help from there.
					if(!$assocHelp[$_GET['helpPage']])
						$assocHelp[$_GET['helpPage']]='index.inc.php';

					//now this line actually snags the tutorial data they're requesting and displays it.
					include('tutorial/'.$assocHelp[$_GET['helpPage']]);
				?>

				
			</div>
		<?PHP include('footer.inc');?>
		</div>
	</body>
</html>
